Repository leonleerl/space-management-tool, pull requests merged in 2025-08, with the labels that each got.

#3 2 template initialisation and scaffolding
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/app/download/page.tsx
  src/app/edit/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/upload/page.tsx
  src/components/Header.tsx
  src/components/index.ts
  src/components/upload/index.ts
  src/components/upload/upload-dragger.tsx
  src/lib/fix.ts
Labels: frontend

#6 4 handsontable demo test
  .gitignore
  package-lock.json
  package.json
  prisma/migrations/20250807064329_first_migration/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  prisma/tsconfig.json
  public/data/contact_list/contact_list.json
  public/data/maps/cells/accounting_finance_cells.json
  public/data/maps/cells/deanery_lvl_2_cells.json
  public/data/maps/cells/economics_cells.json
  public/data/maps/cells/gf_csi_cells.json
  public/data/maps/cells/gf_da_cells.json
  public/data/maps/cells/marketing_cells.json
  public/data/maps/cells/mgmt_&_orgs_cells.json
  public/data/maps/layouts/accounting_finance_layout.json
  public/data/maps/layouts/deanery_lvl_2_layout.json
  public/data/maps/layouts/economics_layout.json
  public/data/maps/layouts/gf_csi_layout.json
  public/data/maps/layouts/gf_da_layout.json
  public/data/maps/layouts/marketing_layout.json
  public/data/maps/layouts/mgmt_&_orgs_layout.json
  public/data/maps/students.json
  src/app/api/accommodation/route.ts
  src/app/api/get-map-data/route.ts
  src/app/api/staff/route.ts
  src/app/edit/page.tsx
  src/components/ConvertRowHeights.tsx
  src/components/HotTableView.tsx
  src/components/edit/ContentMap.tsx
  src/components/edit/MainContent.tsx
  src/components/edit/accommodation/AccFinAcc.tsx
  src/components/edit/accommodation/index.ts
  src/components/edit/index.ts
  src/components/edit/staff/AccFinStaff.tsx
  src/components/edit/staff/index.ts
  src/components/index.ts
  src/hooks/useMapData.ts
  src/hooks/useStaffGrid.ts
  src/lib/loadFilteredContacts.ts
  src/lib/loadFilteredStudents.ts
  src/lib/prisma.ts
  src/lib/schemas/staff.schema.ts
  src/types/constants.ts
  src/types/map.ts
  src/types/member.ts
  src/types/room.ts
  src/types/staff.ts
Labels: enhancement, frontend, backend

#7 feat: MarketingStaff & Marketing Accommodation view are now available
  src/components/edit/ContentMap.tsx
  src/components/edit/accommodation/MarketingAcc.tsx
  src/components/edit/accommodation/index.ts
  src/components/edit/index.ts
  src/components/edit/staff/MarketingStaff.tsx
  src/components/edit/staff/index.ts
Labels: enhancement, frontend

#8 Smt 23 student acc fin frontend
  src/components/edit/ContentMap.tsx
  src/components/edit/student/AccFinStu.tsx
  src/components/edit/student/index.ts
  src/hooks/useStudentGrid.ts
Labels: enhancement, frontend

#9 feat: MOStaff table updated + MOAcc mapview now available
  src/components/edit/ContentMap.tsx
  src/components/edit/accommodation/MOAcc.tsx
  src/components/edit/accommodation/index.ts
  src/components/edit/staff/MOStaff.tsx
  src/components/edit/staff/index.ts
Labels: enhancement, frontend

#10 Smt 24 student acc fin backend
  src/app/api/student/route.ts
  src/app/api/studentType/route.ts
  src/components/edit/MainContent.tsx
  src/components/edit/staff/AccFinStaff.tsx
  src/components/edit/staff/MOStaff.tsx
  src/components/edit/staff/MarketingStaff.tsx
  src/components/edit/student/AccFinStu.tsx
  src/hooks/useStudentGrid.ts
  src/lib/schemas/student.schema.ts
  src/types/department.ts
  src/types/member.ts
  src/types/staff.ts
  src/types/student.ts
  src/types/studentType.ts
Labels: backend

#16 SMT-21 Marketing Student front end feature
  src/components/edit/ContentMap.tsx
  src/components/edit/student/MarketingStu.tsx
  src/components/edit/student/index.ts
Labels: frontend
